In [1]:
import time
import pandas as pd
import numpy as np

CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }

In [2]:
def get_filters():
    """
    Asks user to specify a city, month, and day to analyze.

    Returns:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    """
    print('Hello! Let\'s explore some US bikeshare data!')
    # TO DO: get user input for city (chicago, new york city, washington). HINT: Use a while loop to handle invalid inputs
    while(True):
        city = input("\n Which city do you want to explore ? New York City , Chicago or Washington?\n")
        city = city.lower()
        if city in ['chicago','new york city','washington']:
            break
        else:
            print("wrong city!")
        
    # TO DO: get user input for month (all, january, february, ... , june)
    while(True):
        month = input("\nWhich month do you want to filter by?\n")
        month = month.lower()
        if month in ['all','january','february','march','april','may','june']:
            break
        else:
            print("wrong month!")

    # TO DO: get user input for day of week (all, monday, tuesday, ... sunday)
    while(True):
        day = input("\nWhich day do you want to filter by?\n")
        day = day.lower()
        if day in ['all','monday','tuesday','wednesday','thursday','friday','saturday','sunday']:
            break
        else:
            print("wrong day!")

    print('-'*40)
    return city, month, day

In [3]:
def load_data(city, month, day):
    """
    Loads data for the specified city and filters by month and day if applicable.

    Args:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    Returns:
        df - Pandas DataFrame containing city data filtered by month and day
    """

    # load data file into a dataframe
    df = pd.read_csv(CITY_DATA[city])

    # convert the Start Time column to datetime
    df['Start Time'] = pd.to_datetime(df['Start Time'])

    # extract month and day of week from Start Time to create new columns
    df['month'] = df['Start Time'].dt.month
    df['day_of_week'] = df['Start Time'].dt.day_name()

    # filter by month if applicable
    if month != 'all':
        # use the index of the months list to get the corresponding int
        months = ['january', 'february', 'march', 'april', 'may', 'june']
        month = months.index(month) + 1

        # filter by month to create the new dataframe
        df = df[df['month'] == month]

    # filter by day of week if applicable
    if day != 'all':
        # filter by day of week to create the new dataframe
        df = df[df['day_of_week'] == day.title()]

    return df

In [4]:
def time_stats(df):
    """Displays statistics on the most frequent times of travel."""

    print('\nCalculating The Most Frequent Times of Travel...\n')
    start_time = time.time()

    # TO DO: display the most common month
    most_common_month = df['month'].mode()[0]
    print("The Most Common Months : ",most_common_month)

    # TO DO: display the most common day of week
    most_common_day = df['day_of_week'].mode()[0]
    print("The Most Common Day : ",most_common_day)

    # TO DO: display the most common start hour
    df['hour'] = df['Start Time'].dt.hour
    most_common_start_hour = df['hour'].mode()[0]
    print("The Most Common Start Hour : ",most_common_start_hour)

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [5]:
def station_stats(df):
    """Displays statistics on the most popular stations and trip."""

    print('\nCalculating The Most Popular Stations and Trip...\n')
    start_time = time.time()

    # TO DO: display most commonly used start station
    most_common_start_station = df['Start Station'].mode()[0]
    print("The Most Common Start Station : ",most_common_start_station)

    # TO DO: display most commonly used end station
    most_common_used_end_station = df['End Station'].mode()[0]
    print("The Most Common Used End Station : ",most_common_used_end_station)

    # TO DO: display most frequent combination of start station and end station trip
    combination_start_end_trip = most_common_start_station+ " " + most_common_used_end_station
    print("The Most Frequent Combination Of Start Station And End Station Trip : ",combination_start_end_trip)
    
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [6]:
def trip_duration_stats(df):
    """Displays statistics on the total and average trip duration."""

    print('\nCalculating Trip Duration...\n')
    start_time = time.time()

    # TO DO: display total travel time
    total_travel_time = df['Trip Duration'].sum()
    print("The Total Travel Time : ",total_travel_time)  

    # TO DO: display mean travel time
    mean_travel_time = df['Trip Duration'].mean()
    print("The Mean Travel Time : ",mean_travel_time) 

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [23]:

def user_stats(df,city):
    """Displays statistics on bikeshare users."""

    print('\nCalculating User Stats...\n')
    start_time = time.time()

    # TO DO: Display counts of user types
    counts_user_types = df['User Type'].value_counts()
    print("The Counts Of User Types : ",counts_user_types) 
        


    # TO DO: Display earliest, most recent, and most common year of birth
    
    # Display earliest
    if city != 'washington':
        
        # TO DO: Display counts of gender
        counts_gender = df['Gender'].value_counts()
        print("The Counts Of Genders : ",counts_gender) 
    
        earliest_year_of_birth = df['Birth Year'].min()
        print("The Earliest Year Of Birth : ",earliest_year_of_birth) 
    
        # Display most recent
        most_recent = df['Birth Year'].max()
        print("The Most Recent Year Of Birth : ",most_recent) 
    
        # most common year of birth
        most_common_year_of_birth = df['Birth Year'].value_counts().idxmax()
        print('The Most Common Year Of Birth : ', most_common_year_of_birth)
    

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [29]:
'''
    count = 0
    view = input('\nWould you like to view 5 rows of individual trip data? Enter yes or no\n')
    while (view.lower() == 'yes'):
        print(df[count:count+5])
        count = count + 5
        view = input("Do you wish to continue?: ").lower()  

'''    ;

In [25]:
def display_data(df):
    count = 0
    more_data = input('\nWould you like to view 5 rows of individual trip data? Enter yes or no\n')
    while more_data.lower() == 'yes':
        df_part = df.iloc[count: count+5]
        print(df_part)
        count += 5
        more_data = input('\nWould you like to see more data? Please! Enter,  yes   or   no.\n')

In [26]:
def user_stats(df,city):
    """Displays statistics on bikeshare users."""

    print('\nCalculating User Stats...\n')
    start_time = time.time()

    # Display counts of user types
    print('User Type Stats:')
    print(df['User Type'].value_counts())
    if city != 'washington':
        # Display counts of gender
        print('Gender Stats:')
        print(df['Gender'].value_counts())
        # Display earliest, most recent, and most common year of birth
        print('Birth Year Stats:')
        most_common_year = df['Birth Year'].mode()[0]
        print('Most Common Year:',most_common_year)
        most_recent_year = df['Birth Year'].max()
        print('Most Recent Year:',most_recent_year)
        earliest_year = df['Birth Year'].min()
        print('Earliest Year:',earliest_year)
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [27]:
def main():
    while True:
        city, month, day = get_filters()
        df = load_data(city, month, day)

        time_stats(df)
        station_stats(df)
        trip_duration_stats(df)
        user_stats(df,city)
        display_data(df)

        restart = input('\nWould you like to restart? Enter yes or no.\n')
        if restart.lower() != 'yes':
            break

In [28]:
if __name__ == "__main__":
    main()

Hello! Let's explore some US bikeshare data!

 Which city do you want to explore ? New York City , Chicago or Washington?
chicago

Which month do you want to filter by?
may

Which day do you want to filter by?
sunday
----------------------------------------

Calculating The Most Frequent Times of Travel...

The Most Common Months :  5
The Most Common Day :  Sunday
The Most Common Start Hour :  12

This took 0.004838705062866211 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

The Most Common Start Station :  Streeter Dr & Grand Ave
The Most Common Used End Station :  Streeter Dr & Grand Ave
The Most Frequent Combination Of Start Station And End Station Trip :  Streeter Dr & Grand Ave Streeter Dr & Grand Ave

This took 0.002931833267211914 seconds.
----------------------------------------

Calculating Trip Duration...

The Total Travel Time :  10795584
The Mean Travel Time :  1279.7041251778094

This took 0.0 seconds.
----------------------------------------

Calculating User Stats...

User Type Stats:
Subscriber    4551
Customer      3885
Name: User Type, dtype: int64
Gender Stats:
Male      3131
Female    1419
Name: Gender, dtype: int64
Birth Year Stats:
Most Common Year: 1992.0
Most Recent Year: 2000.0
Earliest Year: 1901.0

This took 0.006841182708740234 seconds.
----------------------------------------

Would you like to view 5 rows of individual trip data? Enter yes or no
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
48       906322 2017-05-21 10:03:55  2017-05-21 10:18:17            862
59       750957 2017-05-07 11:14:27  2017-05-07 11:20:55            388
156      994753 2017-05-28 17:34:53  2017-05-28 17:51:32            999
159      823105 2017-05-14 07:14:56  2017-05-14 07:19:35            279
241      832285 2017-05-14 17:55:22  2017-05-14 18:14:10           1128

                Start Station                  End Station   User Type  \
48   McClurg Ct & Illinois St     McClurg Ct & Illinois St  Subscriber
59   McClurg Ct & Illinois St        Rush St & Superior St  Subscriber
156    Halsted St & Roscoe St         Broadway & Ridge Ave  Subscriber
159   Greenwood Ave & 47th St  Cottage Grove Ave & 47th St  Subscriber
241    Green St & Randolph St       Clark St & Schiller St  Subscriber

     Gender  Birth Year  month day_of_week  hour
48     Male      1990.0      5      Sunday    10
59   Female      1987.0      5      Sunday    11
156    Male      1970.0      5      Sunday    17
159    Male      1966.0      5      Sunday     7
241  Female      1985.0      5      Sunday    17

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
283      986517 2017-05-28 10:18:25  2017-05-28 11:22:41           3856
284      750663 2017-05-07 10:41:04  2017-05-07 12:26:37           6333
477      911495 2017-05-21 15:13:30  2017-05-21 15:22:20            530
565      828661 2017-05-14 14:17:51  2017-05-14 14:41:53           1442
750      824443 2017-05-14 10:22:16  2017-05-14 10:41:25           1149

                    Start Station                    End Station   User Type  \
283        Broadway & Sheridan Rd              Clark St & Elm St    Customer
284  Michigan Ave & Congress Pkwy        Streeter Dr & Grand Ave    Customer
477     Michigan Ave & Pearson St       Fairbanks Ct & Grand Ave    Customer
565         Michigan Ave & Oak St  Halsted St & Blackhawk St (*)  Subscriber
750          Broadway & Barry Ave          Michigan Ave & Oak St    Customer

    Gender  Birth Year  month day_of_week  hour
283    NaN         NaN      5      Sunday    10
284    NaN         NaN      5      Sunday    10
477    NaN         NaN      5      Sunday    15
565   Male      1971.0      5      Sunday    14
750    NaN         NaN      5      Sunday    10

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
765      992206 2017-05-28 15:35:31  2017-05-28 15:41:38            367
773      906221 2017-05-21 09:51:42  2017-05-21 10:06:35            893
781      830443 2017-05-14 15:53:31  2017-05-14 16:19:46           1575
821      909818 2017-05-21 13:33:46  2017-05-21 13:40:41            415
838      753940 2017-05-07 15:25:13  2017-05-07 15:29:40            267

                   Start Station                  End Station   User Type  \
765  Campbell Ave & Montrose Ave  Oakley Ave & Irving Park Rd  Subscriber
773      Broadway & Cornelia Ave   Damen Ave & Wellington Ave    Customer
781              Millennium Park              Millennium Park    Customer
821    Leavitt St & Armitage Ave      Damen Ave & Cortland St    Customer
838           Wells St & Polk St         Canal St & Taylor St  Subscriber

     Gender  Birth Year  month day_of_week  hour
765  Female      1982.0      5      Sunday    15
773     NaN         NaN      5      Sunday     9
781     NaN         NaN      5      Sunday    15
821     NaN         NaN      5      Sunday    13
838    Male      1987.0      5      Sunday    15

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
896      994153 2017-05-28 17:07:00  2017-05-28 17:27:13           1213
914      752085 2017-05-07 12:53:06  2017-05-07 13:17:53           1487
941      828442 2017-05-14 14:06:59  2017-05-14 14:12:26            327
962      992693 2017-05-28 15:59:41  2017-05-28 16:34:27           2086
996      830475 2017-05-14 15:55:07  2017-05-14 16:12:04           1017

                    Start Station                   End Station   User Type  \
896           Buckingham Fountain               Millennium Park    Customer
914           Theater on the Lake       Streeter Dr & Grand Ave    Customer
941  Sheffield Ave & Kingsbury St   Sheffield Ave & Webster Ave  Subscriber
962       Clark St & Armitage Ave  Milwaukee Ave & Wabansia Ave    Customer
996    Clifton Ave & Armitage Ave       Ogden Ave & Chicago Ave    Customer

    Gender  Birth Year  month day_of_week  hour
896    NaN         NaN      5      Sunday    17
914    NaN         NaN      5      Sunday    12
941   Male      1990.0      5      Sunday    14
962    NaN         NaN      5      Sunday    15
996    NaN         NaN      5      Sunday    15

Would you like to see more data? Please! Enter,  yes   or   no.
yes
      Unnamed: 0          Start Time             End Time  Trip Duration  \
1070      994253 2017-05-28 17:11:39  2017-05-28 17:17:50            371
1119      824816 2017-05-14 10:48:23  2017-05-14 10:59:00            637
1143      833806 2017-05-14 21:26:41  2017-05-14 21:48:33           1312
1170      989036 2017-05-28 12:36:21  2017-05-28 12:50:42            861
1176      994612 2017-05-28 17:29:10  2017-05-28 17:50:29           1279

                  Start Station                      End Station   User Type  \
1070        Clark St & Grace St  Pine Grove Ave & Irving Park Rd    Customer
1119  Damen Ave & Charleston St    Greenview Ave & Diversey Pkwy  Subscriber
1143    Streeter Dr & Grand Ave              Theater on the Lake  Subscriber
1170         Daley Center Plaza          Franklin St & Monroe St    Customer
1176  Lake Shore Dr & Monroe St        Columbus Dr & Randolph St  Subscriber

     Gender  Birth Year  month day_of_week  hour
1070    NaN         NaN      5      Sunday    17
1119   Male      1986.0      5      Sunday    10
1143   Male      1991.0      5      Sunday    21
1170    NaN         NaN      5      Sunday    12
1176   Male      1959.0      5      Sunday    17

Would you like to see more data? Please! Enter,  yes   or   no.
yes
      Unnamed: 0          Start Time             End Time  Trip Duration  \
1190      908578 2017-05-21 12:30:16  2017-05-21 12:36:41            385
1235      910201 2017-05-21 13:56:57  2017-05-21 13:59:54            177
1275      906636 2017-05-21 10:31:05  2017-05-21 10:51:08           1203
1289      910009 2017-05-21 13:44:21  2017-05-21 13:49:14            293
1342      915158 2017-05-21 22:47:13  2017-05-21 22:56:22            549

                  Start Station                      End Station   User Type  \
1190      Canal St & Madison St        Desplaines St & Kinzie St  Subscriber
1235       Wabash Ave & 16th St        Wabash Ave & Roosevelt Rd  Subscriber
1275  Lake Shore Dr & Monroe St           State St & Randolph St    Customer
1289         Clark St & Lake St  Cityfront Plaza Dr & Pioneer Ct  Subscriber
1342    Ogden Ave & Chicago Ave           Damen Ave & Pierce Ave  Subscriber

     Gender  Birth Year  month day_of_week  hour
1190   Male      1991.0      5      Sunday    12
1235   Male      1990.0      5      Sunday    13
1275    NaN         NaN      5      Sunday    10
1289   Male      1989.0      5      Sunday    13
1342   Male      1991.0      5      Sunday    22

Would you like to see more data? Please! Enter,  yes   or   no.
yes
      Unnamed: 0          Start Time             End Time  Trip Duration  \
1350      996266 2017-05-28 18:48:33  2017-05-28 20:38:20           6587
1356      909742 2017-05-21 13:30:47  2017-05-21 13:53:55           1388
1372      831088 2017-05-14 16:30:50  2017-05-14 16:45:50            900
1433      910906 2017-05-21 14:37:19  2017-05-21 14:57:03           1184
1452      824687 2017-05-14 10:39:28  2017-05-14 11:06:38           1630

                 Start Station                End Station   User Type  Gender  \
1350   Broadway & Cornelia Ave    Broadway & Cornelia Ave    Customer     NaN
1356     Michigan Ave & Oak St      Michigan Ave & Oak St    Customer     NaN
1372     Dayton St & North Ave   Kingsbury St & Kinzie St    Customer     NaN
1433   Streeter Dr & Grand Ave  Larrabee St & Webster Ave  Subscriber  Female
1452  Lincoln Ave & Leavitt St   Wells St & Evergreen Ave  Subscriber    Male

      Birth Year  month day_of_week  hour
1350         NaN      5      Sunday    18
1356         NaN      5      Sunday    13
1372         NaN      5      Sunday    16
1433      1988.0      5      Sunday    14
1452      1991.0      5      Sunday    10

Would you like to see more data? Please! Enter,  yes   or   no.
yes
      Unnamed: 0          Start Time             End Time  Trip Duration  \
1500      828610 2017-05-14 14:15:51  2017-05-14 14:36:25           1234
1513      829709 2017-05-14 15:13:53  2017-05-14 16:03:59           3006
1517      755386 2017-05-07 17:34:51  2017-05-07 17:59:18           1467
1527      911793 2017-05-21 15:30:50  2017-05-21 15:36:33            343
1533      989016 2017-05-28 12:35:22  2017-05-28 12:53:06           1064

                     Start Station                    End Station   User Type  \
1500             Clark St & Elm St      Clark St & Wrightwood Ave    Customer
1513   Sheffield Ave & Webster Ave     Clifton Ave & Armitage Ave    Customer
1517       Franklin St & Monroe St         St. Clair St & Erie St    Customer
1527  Ashland Ave & Wrightwood Ave  Sheffield Ave & Fullerton Ave  Subscriber
1533   Western Ave & Winnebago Ave        Damen Ave & Division St    Customer

     Gender  Birth Year  month day_of_week  hour
1500    NaN         NaN      5      Sunday    14
1513    NaN         NaN      5      Sunday    15
1517    NaN         NaN      5      Sunday    17
1527   Male      1992.0      5      Sunday    15
1533    NaN         NaN      5      Sunday    12

Would you like to see more data? Please! Enter,  yes   or   no.
no

Would you like to restart? Enter yes or no.
yes
Hello! Let's explore some US bikeshare data!

 Which city do you want to explore ? New York City , Chicago or Washington?
no
wrong city!

 Which city do you want to explore ? New York City , Chicago or Washington?
Chicago

Which month do you want to filter by?
may

Which day do you want to filter by?
tuesday
----------------------------------------

Calculating The Most Frequent Times of Travel...

The Most Common Months :  5
The Most Common Day :  Tuesday
The Most Common Start Hour :  17

This took 0.0058629512786865234 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

The Most Common Start Station :  Clinton St & Washington Blvd
The Most Common Used End Station :  Clinton St & Madison St
The Most Frequent Combination Of Start Station And End Station Trip :  Clinton St & Washington Blvd Clinton St & Madison St

This took 0.0029327869415283203 seconds.
----------------------------------------

Calculating Trip Duration...

The Total Travel Time :  8531768
The Mean Travel Time :  822.8942901234568

This took 0.0 seconds.
----------------------------------------

Calculating User Stats...

User Type Stats:
Subscriber    8997
Customer      1371
Name: User Type, dtype: int64
Gender Stats:
Male      6910
Female    2090
Name: Gender, dtype: int64
Birth Year Stats:
Most Common Year: 1989.0
Most Recent Year: 2000.0
Earliest Year: 1899.0

This took 0.005867481231689453 seconds.
----------------------------------------

Would you like to view 5 rows of individual trip data? Enter yes or no
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
13      1023296 2017-05-30 15:46:18  2017-05-30 15:52:12            354
17       931608 2017-05-23 08:08:25  2017-05-23 08:11:09            164
20       849468 2017-05-16 06:36:17  2017-05-16 06:59:34           1397
111      850260 2017-05-16 07:32:12  2017-05-16 07:56:24           1452
138      769275 2017-05-09 12:58:51  2017-05-09 13:10:15            684

                  Start Station                   End Station   User Type  \
13   Larrabee St & Kingsbury St             Clark St & Elm St  Subscriber
17      Damen Ave & Cortland St  Marshfield Ave & Cortland St  Subscriber
20        Michigan Ave & Oak St   Halsted St & Wrightwood Ave  Subscriber
111        Broadway & Barry Ave      LaSalle St & Illinois St  Subscriber
138   Franklin St & Chicago Ave        St. Clair St & Erie St  Subscriber

     Gender  Birth Year  month day_of_week  hour
13     Male      1985.0      5     Tuesday    15
17     Male      1990.0      5     Tuesday     8
20   Female      1992.0      5     Tuesday     6
111    Male      1993.0      5     Tuesday     7
138    Male      1980.0      5     Tuesday    12

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
146      862604 2017-05-16 19:21:46  2017-05-16 19:35:55            849
162      863352 2017-05-16 20:04:57  2017-05-16 20:26:29           1292
176      854604 2017-05-16 12:48:26  2017-05-16 13:03:21            895
189      711092 2017-05-02 16:44:29  2017-05-02 17:06:16           1307
212      772419 2017-05-09 17:42:45  2017-05-09 17:54:27            702

                           Start Station                  End Station  \
146          Oakley Ave & Irving Park Rd     Damen Ave & Clybourn Ave
162                      Montrose Harbor  Halsted St & Wrightwood Ave
176                  Wells St & Huron St     McClurg Ct & Illinois St
189  Mies van der Rohe Way & Chicago Ave  Lake Shore Dr & Belmont Ave
212            Columbus Dr & Randolph St      Clinton St & Madison St

      User Type  Gender  Birth Year  month day_of_week  hour
146  Subscriber  Female      1955.0      5     Tuesday    19
162  Subscriber    Male      1993.0      5     Tuesday    20
176    Customer     NaN         NaN      5     Tuesday    12
189    Customer     NaN         NaN      5     Tuesday    16
212  Subscriber    Male      1987.0      5     Tuesday    17

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
231      852040 2017-05-16 08:48:38  2017-05-16 08:58:08            570
233      864976 2017-05-16 23:24:39  2017-05-16 23:29:39            300
257      859359 2017-05-16 17:23:49  2017-05-16 17:36:05            736
282     1024744 2017-05-30 16:56:00  2017-05-30 17:00:22            262
285      767209 2017-05-09 07:32:24  2017-05-09 07:55:21           1377

                       Start Station                     End Station  \
231         Kingsbury St & Kinzie St        McClurg Ct & Illinois St
233  Blackstone Ave & Hyde Park Blvd             Ellis Ave & 53rd St
257             Rhodes Ave & 32nd St           Shields Ave & 31st St
282      Cottage Grove Ave & 43rd St    Woodlawn Ave & Lake Park Ave
285             Troy St & Elston Ave  Sheffield Ave & Wellington Ave

      User Type  Gender  Birth Year  month day_of_week  hour
231  Subscriber  Female      1989.0      5     Tuesday     8
233  Subscriber    Male      1987.0      5     Tuesday    23
257  Subscriber    Male      1991.0      5     Tuesday    17
282  Subscriber    Male      1989.0      5     Tuesday    16
285  Subscriber  Female      1985.0      5     Tuesday     7

Would you like to see more data? Please! Enter,  yes   or   no.
yes

     Unnamed: 0          Start Time             End Time  Trip Duration  \
344      932889 2017-05-23 11:12:06  2017-05-23 11:40:10           1684
376      849614 2017-05-16 06:50:35  2017-05-16 06:53:41            186
377      770435 2017-05-09 16:02:31  2017-05-09 16:11:46            555
492      773083 2017-05-09 18:17:43  2017-05-09 18:38:57           1274
519      850711 2017-05-16 07:52:53  2017-05-16 08:00:58            485

                  Start Station                  End Station   User Type  \
344      State St & Harrison St            Adler Planetarium    Customer
376   Claremont Ave & Hirsch St       Damen Ave & Pierce Ave  Subscriber
377    Canal St & Monroe St (*)        Dearborn St & Erie St  Subscriber
492       Michigan Ave & Oak St  Lake Shore Dr & Belmont Ave    Customer
519  Halsted St & Diversey Pkwy     Halsted St & Dickens Ave  Subscriber

     Gender  Birth Year  month day_of_week  hour
344     NaN         NaN      5     Tuesday    11
376  Female      1986.0      5     Tuesday     6
377    Male      1989.0      5     Tuesday    16
492     NaN         NaN      5     Tuesday    18
519    Male      1985.0      5     Tuesday     7

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
554      709636 2017-05-02 13:08:06  2017-05-02 13:32:17           1451
574      860251 2017-05-16 17:50:22  2017-05-16 18:01:17            655
595     1019234 2017-05-30 09:15:39  2017-05-30 09:21:46            367
668      855429 2017-05-16 13:59:14  2017-05-16 14:47:21           2887
702      774924 2017-05-09 23:24:44  2017-05-09 23:28:45            241

                Start Station             End Station   User Type  Gender  \
554            Dusable Harbor    Rush St & Hubbard St    Customer     NaN
574   Halsted St & Maxwell St  Michigan Ave & 18th St  Subscriber  Female
595  LaSalle St & Illinois St   Canal St & Madison St  Subscriber    Male
668    State St & Harrison St     Buckingham Fountain    Customer     NaN
702      Clark St & North Ave   Ritchie Ct & Banks St  Subscriber    Male

     Birth Year  month day_of_week  hour
554         NaN      5     Tuesday    13
574      1992.0      5     Tuesday    17
595      1989.0      5     Tuesday     9
668         NaN      5     Tuesday    13
702      1990.0      5     Tuesday    23

Would you like to see more data? Please! Enter,  yes   or   no.
yes
     Unnamed: 0          Start Time             End Time  Trip Duration  \
761     1028141 2017-05-30 18:56:11  2017-05-30 19:05:52            581
813     1017365 2017-05-30 07:45:32  2017-05-30 07:47:56            144
860      709358 2017-05-02 12:13:31  2017-05-02 12:27:05            814
917      850413 2017-05-16 07:39:05  2017-05-16 07:43:53            288
933     1029944 2017-05-30 21:45:13  2017-05-30 21:54:22            549

                Start Station                      End Station   User Type  \
761  LaSalle St & Illinois St          Aberdeen St & Monroe St  Subscriber
813  Kingsbury St & Kinzie St           Kingsbury St & Erie St  Subscriber
860       Morgan St & Lake St  Cityfront Plaza Dr & Pioneer Ct  Subscriber
917   Clinton St & Madison St               Daley Center Plaza  Subscriber
933     LaSalle St & Adams St              Morgan St & Polk St  Subscriber

     Gender  Birth Year  month day_of_week  hour
761    Male      1985.0      5     Tuesday    18
813    Male      1982.0      5     Tuesday     7
860  Female      1977.0      5     Tuesday    12
917    Male      1987.0      5     Tuesday     7
933    Male      1966.0      5     Tuesday    21

Would you like to see more data? Please! Enter,  yes   or   no.
no

Would you like to restart? Enter yes or no.
no